//
// Created by ynx on 2020-02-09.
//

#ifndef RAFT_RPC_TYPE_H
#define RAFT_RPC_TYPE_H

enum RPC_TYPE {
    REQUEST_VOTE, APPEND_ENTRY, RESP_VOTE, RESP_APPEND, CLIENT_APPLY, CLIENT_QUERY, RESP_CLIENT_APPLY, RESP_CLIENT_QUERY, ERROR
};

#endif //RAFT_RPC_TYPE_H
